
[interact_key]
	#These whitelist blocks can be interacted with when the interact key is pressed
	InteractKeyWhitelistBlocks = []
	#These whitelist entities can be interacted with when the interact key is pressed
	InteractKeyWhitelistEntities = []
	#These blacklist blocks can be interacted with when the interact key is pressed
	InteractKeyBlacklistBlocks = []
	#These blacklist entities can be interacted with when the interact key is pressed
	InteractKeyBlacklistEntities = []

[base_multiplier]
	#All base damage number is multiplied by this factor
	#Range: 0.0 ~ 1.7976931348623157E308
	DamageBaseMultiplier = 1.0
	#All armor ignore damage number is multiplied by this factor
	#Range: 0.0 ~ 1.7976931348623157E308
	ArmorIgnoreBaseMultiplier = 1.0
	#All head shot damage number is multiplied by this factor
	#Range: 0.0 ~ 1.7976931348623157E308
	HeadShotBaseMultiplier = 1.0

[misc]
	#The entity's head hitbox during the headshot
	#Format: touhou_little_maid:maid [-0.5, 1.0, -0.5, 0.5, 1.5, 0.5]
	HeadShotAABB = []
	#The maximum stack size of ammo that the ammo box can hold
	#Range: > 1
	AmmoBoxStackSize = 3
	#The gun pack that the client player needs to download, needs to fill in the URL and the SHA1 value of the file
	ClientGunPackDownloadUrls = []

